#include "OBJWriter.h"

#include <fstream>
#include <iostream> // FIXME

OBJWriter::OBJWriter ()
{
}

OBJWriter::~OBJWriter ()
{
}

int
OBJWriter::write (const std::string& file_name, const PointCloud& cloud, const bool binary)
{
  std::ofstream output (file_name.c_str (), std::ofstream::out);
  PointCloud::const_iterator it;

  if (binary) {
    std::cerr << "Binary mode not supported by OBJ file format" << std::endl;
    return -1;
  }
  if (!output.is_open ()) {
    std::cerr << "Failed to open file " << file_name << std::endl;
    return -1;
  }

  output << "# File generated by libcloud" << std::endl;
  output << "g Point_Model" << std::endl;

  for (it = cloud.begin (); it != cloud.end (); ++it) {
    output << "v " << (*it).x << " " << (*it).y << " " << (*it).z << std::endl;
  }

  return 0;
}